use NeonMixer

CREATE TABLE Users(
userId INTEGER NOT NULL IDENTITY(1,1),
login NVARCHAR(64) NOT NULL,
password NVARCHAR(64) NOT NULL,
CONSTRAINT PK_Users PRIMARY KEY(userId))

CREATE TABLE Mix(
mixId INTEGER NOT NULL IDENTITY(1,1),
name NVARCHAR(64) NOT NULL,
PGVG INTEGER NOT NULL,
volOfFlud integer NOT NULL,
water integer NOT NULL,
strengthOfNicoBase INTEGER NOT NULL,
nicoContent INTEGER NOT NULL,
CONSTRAINT PK_Mix PRIMARY KEY(mixId))

CREATE TABLE UserMix(
userId INTEGER NOT NULL,
mixId INTEGER NOT NULL,
CONSTRAINT PK_UserMix PRIMARY KEY(userId, mixId),
CONSTRAINT FK_UserMix_User FOREIGN KEY(userId)
	REFERENCES Users(userId)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
CONSTRAINT FK_UserMix_Mix FOREIGN KEY(mixId)
	REFERENCES Mix(mixId)
	ON DELETE CASCADE
	ON UPDATE CASCADE,)

CREATE TABLE FlavorInMix(
mixId INTEGER NOT NULL,
flavorName NVARCHAR(64) NOT NULL,
flavorContent INTEGER NOT NULL,
CONSTRAINT PK_FlavorInMix PRIMARY KEY(mixId, flavorName, flavorContent),
CONSTRAINT FK_FlavorInMix_Mix FOREIGN KEY(mixId)
	REFERENCES Mix(mixId)
	ON DELETE CASCADE
	ON UPDATE CASCADE,)

INSERT INTO Users (login, password) VALUES ('admin', 'admin'), ('KeeperXTL', '111111')